import PDFDocument from 'pdfkit';
import { formatUSD } from './currency.js';

export const generatePDFReceipt = (tx) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      doc.fontSize(20).text('OFFICIAL RECEIPT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Receipt ID: ${tx.tx_id}`, { align: 'right' });
      doc.text(`Date: ${new Date(tx.timestamp).toLocaleString()}`, { align: 'right' });
      doc.moveDown(2);

      doc.fontSize(14).text('Transaction Details', { underline: true });
      doc.moveDown(0.5);
      
      const typeStr = tx.type === 'INCOME' ? 'Income / Deposit' : 'Expense / Withdrawal';
      doc.fontSize(12).text(`Type: ${typeStr}`);
      doc.text(`Logged by: ${tx.username} (ID: ${tx.user_id})`);
      doc.text(`Reason: ${tx.reason}`);
      doc.moveDown(1.5);

      doc.fontSize(14).text('Financial Summary', { underline: true });
      doc.moveDown(0.5);
      
      doc.fontSize(12);
      const sign = tx.type === 'INCOME' ? '+' : '-';
      doc.text(`Amount: ${sign}${formatUSD(tx.amount)}`);
      doc.text(`Balance After: ${formatUSD(tx.balance_after)}`);
      
      doc.moveDown(3);
      doc.fontSize(10).text('Generated by Finance Tracker Bot', { align: 'center', color: 'gray' });

      doc.end();
    } catch (error) { reject(error); }
  });
};